# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: t.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='t.proto',
  package='t',
  serialized_pb='\n\x07t.proto\x12\x01t\"+\n\x06\x63ommon\x12\x0f\n\x04user\x18\x01 \x02(\r:\x01\x30\x12\x10\n\x06\x64\x65vice\x18\x02 \x02(\t:\x00\"\x16\n\x03ret\x12\x0f\n\x04stat\x18\x01 \x02(\x05:\x01\x30\x32+\n\tt_service\x12\x1e\n\theartbeat\x12\t.t.common\x1a\x06.t.retB\x0e\n\x05\x63om.tB\x02t_\x80\x01\x01')




_COMMON = _descriptor.Descriptor(
  name='common',
  full_name='t.common',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='t.common.user', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='t.common.device', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=57,
)


_RET = _descriptor.Descriptor(
  name='ret',
  full_name='t.ret',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stat', full_name='t.ret.stat', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=59,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['common'] = _COMMON
DESCRIPTOR.message_types_by_name['ret'] = _RET

class common(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COMMON

  # @@protoc_insertion_point(class_scope:t.common)

class ret(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RET

  # @@protoc_insertion_point(class_scope:t.ret)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\005com.tB\002t_\200\001\001')
# @@protoc_insertion_point(module_scope)
